/** @type {import('tailwindcss').Config} */
export default {
  content: ['./index.html', './src/**/*.{js,jsx}'],
  theme: {
    extend: {
      colors: {
        'primary': '#000a1e',
        'primary-container': '#002147',
        'on-primary': '#ffffff',
        'on-primary-container': '#708ab5',
        'primary-fixed': '#d6e3ff',
        'primary-fixed-dim': '#aec7f6',
        'on-primary-fixed': '#001b3d',
        'on-primary-fixed-variant': '#2d476f',
        'secondary': '#0054cd',
        'secondary-container': '#316ee9',
        'on-secondary': '#ffffff',
        'on-secondary-container': '#fefcff',
        'secondary-fixed': '#dae2ff',
        'secondary-fixed-dim': '#b2c5ff',
        'on-secondary-fixed': '#001847',
        'on-secondary-fixed-variant': '#0040a1',
        'tertiary': '#180500',
        'tertiary-container': '#3d1500',
        'on-tertiary': '#ffffff',
        'on-tertiary-container': '#b97958',
        'tertiary-fixed': '#ffdbcb',
        'tertiary-fixed-dim': '#ffb691',
        'on-tertiary-fixed': '#341100',
        'on-tertiary-fixed-variant': '#6c391d',
        'surface': '#f8f9ff',
        'surface-dim': '#ccdbf3',
        'surface-bright': '#f8f9ff',
        'surface-variant': '#d5e3fc',
        'surface-tint': '#465f88',
        'surface-container-lowest': '#ffffff',
        'surface-container-low': '#eff4ff',
        'surface-container': '#e6eeff',
        'surface-container-high': '#dce9ff',
        'surface-container-highest': '#d5e3fc',
        'on-surface': '#0d1c2e',
        'on-surface-variant': '#44474e',
        'inverse-surface': '#233144',
        'inverse-on-surface': '#eaf1ff',
        'inverse-primary': '#aec7f6',
        'background': '#f8f9ff',
        'on-background': '#0d1c2e',
        'outline': '#74777f',
        'outline-variant': '#c4c6cf',
        'error': '#ba1a1a',
        'error-container': '#ffdad6',
        'on-error': '#ffffff',
        'on-error-container': '#93000a',
      },
      borderRadius: {
        DEFAULT: '0.125rem',
        sm: '0.125rem',
        md: '0.375rem',
        lg: '0.25rem',
        xl: '0.5rem',
        '2xl': '0.75rem',
        full: '9999px',
      },
      fontFamily: {
        headline: ['Manrope', 'sans-serif'],
        body: ['Inter', 'sans-serif'],
        label: ['Inter', 'sans-serif'],
      },
      boxShadow: {
        surface: '0px 12px 32px -4px rgba(13,28,46,0.06)',
      },
    },
  },
  plugins: [],
};

